import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/layout/Navbar";
import Category from "./components/layout/Category";
import Footer from "./components/layout/Footer";

import { CartProvider } from "./lib/cartContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={inter.className}
    >
      <body className="min-h-full flex flex-col">
        <CartProvider>
          <div >
            <Navbar />
            <Category />

          </div>
          
          {children}
        </CartProvider>
        <Footer/>
      </body>
    </html>
  );
}
